<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'About' => '',
    'About {sitename}' => '',
    'Actions' => '',
    'Active' => '',
    'Add attribute' => '',
    'Add project' => '',
    'Add user' => '',
    'Ancestor' => '',
    'Attribute' => '',
    'Attribute Option' => '',
    'Attributes' => '',
    'Browse cards list' => '',
    'Cancel' => '',
    'Card' => '',
    'Card attributes' => '',
    'Cards' => '',
    'Contact message' => '',
    'Contact us' => '',
    'Create a new user' => '',
    'Create attribute' => '',
    'Create new attribute' => '',
    'Create new project' => '',
    'Create project' => '',
    'Create user' => '',
    'Date' => '',
    'Description' => '',
    'E-mail' => '',
    'E-mail or username' => '',
    'Error' => '',
    'Error ' => '',
    'Expires' => '',
    'Home' => '',
    'ID' => '',
    'ISO Code' => '',
    'Invalid project. You\'re trying to load a project that does not exist.' => '',
    'Invalid request. Please do not repeat this request again.' => '',
    'Invalid user. You\'re trying to load a user that does not exist.' => '',
    'Invalid username, e-mail or password.' => '',
    'Key' => '',
    'Language' => '',
    'Login' => '',
    'Login/Register' => '',
    'Logout' => '',
    'Manage card attributes' => '',
    'Manage projects' => '',
    'Manage users' => '',
    'Message' => '',
    'Multi-value' => '',
    'Name' => '',
    'New account registered' => '',
    'Objective' => '',
    'Password' => '',
    'Project' => '',
    'Projects' => '',
    'Reason for contact' => '',
    'Register' => '',
    'Register new account' => '',
    'Registration' => '',
    'Repeat password' => '',
    'Role' => '',
    'Save' => '',
    'Send' => '',
    'Status' => '',
    'String' => '',
    'Unknown role' => '',
    'Update project' => '',
    'Update project {name}' => '',
    'Update user' => '',
    'Update {username}\'s information' => '',
    'User' => '',
    'Username' => '',
    'Users' => '',
    'Your e-mail (not shared)' => '',
    'Your name' => '',
);
