SET AUTOCOMMIT=0;
START TRANSACTION;

CREATE TABLE IF NOT EXISTS `wt_cs_cards` (
  `id` int(11) NOT NULL auto_increment,
  `revision` float default '0.01',
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `author` varchar(15) collate utf8_unicode_ci default NULL,
  `status` enum('concept','discuss','playtest','approved','official','halt','restricted','rejected') collate utf8_unicode_ci default 'concept',
  `image` varchar(255) collate utf8_unicode_ci default NULL,
  `cardname` varchar(30) collate utf8_unicode_ci default NULL,
  `faction` enum('Gaia','House of Nobles','Undead','Red Banner','Empire') collate utf8_unicode_ci default NULL,
  `type` enum('unit','event','spell','enchantment','equipment','artifact') collate utf8_unicode_ci default NULL,
  `subtype` varchar(30) collate utf8_unicode_ci default NULL,
  `cost` int(11) default NULL,
  `threshold` int(11) default NULL,
  `attack` int(11) default NULL,
  `defense` int(11) default NULL,
  `rules` text collate utf8_unicode_ci,
  `flavor` text collate utf8_unicode_ci,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=81 ;

INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (1, 0.08, '2011-08-01 13:59:37', 'pennomi', 'playtest', 'cards/1-1.png', 'Elvish Shaman', 'Gaia', 'unit', 'Elf, Caster', 3, 1, 1, 2, '[m]: Prevent up to 2 damage to target creature.)', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (2, 0.05, '2011-08-01 15:38:52', 'Q_x', 'rejected', ' ', 'Love is a Shield', 'Gaia', 'event', ' ', 1, 1, 0, 0, 'Target defender gets +0/+x where x is equal to the creature''s ATK.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (3, 0.03, '2011-04-24 09:49:40', 'pennomi', 'playtest', 'cards/3-1.png', 'Elvish Fighter', 'Gaia', 'unit', 'Elf', 2, 0, 2, 1, ' ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (4, 0.06, '2011-08-01 14:32:27', 'Q_x', 'playtest', 'cards/4-1.png', 'Algae Armor', 'Gaia', 'equipment', 'Armor', 2, 0, 0, 0, 'Equipped creature gets +0/+2.\r\n\r\nIf it is a Merfolk it also gets <i>"Guard (This creature can defend against multiple attackers.)"</i>', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (5, 0.07, '2011-08-01 13:22:49', 'snowdrop', 'playtest', 'cards/5-2.png', 'Elvish Archer', 'Gaia', 'unit', 'Elf', 3, 0, 2, 1, 'Ranged (This unit can defend against units with Flying.)\r\n\r\nOffensive Strike - Defenders only strike\r\nback if they survive.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (6, 0.04, '2011-04-24 10:06:16', 'pennomi', 'playtest', ' ', 'Elvish Scout', 'Gaia', 'unit', 'Elf, Rider', 4, 0, 2, 2, 'Quick (This creature does not mark when moving and may move twice.)', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (7, 0.05, '2011-05-11 19:50:46', 'pennomi', 'playtest', 'cards/7-2.png', 'Soulharvester', 'Undead', 'unit', 'Caster', 4, 2, 2, 2, 'Once per turn, when an ally non-token creature of cost 3 or lower would be put in the graveyard, you may instead place it as a Resource Card on your smallest Resource Pile.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (8, 0.05, '2011-07-19 21:22:14', 'pennomi', 'playtest', 'cards/8-2.png', 'Elvish Marksman', 'Gaia', 'unit', 'Elf', 5, 1, 2, 2, 'Offensive Strike (Enemy defender only strikes back in combat if it survives.)\r\n\r\n(m), 1: Deal 1 damage to target attacker that is being defended against by an ally.\r\n', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (9, 0.07, '2011-08-01 14:07:20', 'pennomi', 'playtest', ' ', 'Sharpshooter', 'Gaia', 'unit', 'Elf', 4, 2, 2, 2, 'Ranged (This creature may defend against flying creatures)\r\n\r\nWhen there are no local allies Elvish Sharpshooter may attack a creature instead of a player.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (10, 0.04, '2011-04-24 10:07:15', 'pennomi', 'playtest', 'cards/10-1.png', 'Elvish Ranger', 'Gaia', 'unit', 'Elf', 4, 1, 2, 3, 'Stealth 2 (Only creatures with a gold cost of 2 or more can defend against this creature.)', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (11, 0.06, '2011-08-01 13:37:22', 'snowdrop', 'playtest', 'cards/11-3.png', 'Elvish Druid', 'Gaia', 'unit', 'Elf, Caster', 4, 2, 2, 2, '[m]: Target creatures attack is reduced to half (rounded up) until end of turn.\r\n\r\n[m]: Target creature can''t move until end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (12, 0.03, '2011-07-19 21:10:53', 'irrevenant', 'playtest', ' ', 'Soul Twist', 'Undead', 'enchantment', ' ', 2, 1, 0, 0, 'The values of enchanted creatures ATK and DEF change places with each other. This also applies to all effects that modify them.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (13, 0.05, '2011-07-19 21:22:32', 'Q_x', 'playtest', 'cards/13-1.png', 'Metamorphed', 'Undead', 'enchantment', ' ', 4, 3, 0, 0, 'Mark target ally creature, then target another ally creature in same front Put this card into play next to it, treating it as an exact copy of the targeted creatures abilities and all attached cards to it.\r\n\r\nPut both the copy and the targeted creature into the graveyard of one should be placed there.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (14, 0.05, '2011-04-24 10:46:49', 'irrevenant', 'playtest', ' ', 'Share the Load', 'Red Banner', 'enchantment', ' ', 4, 2, 0, 0, 'You may redistribute x amount of damage dealt to target creatures in combat amongst other ally creatures in the same front.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (15, 0.05, '2011-05-11 18:47:21', 'pennomi', 'playtest', ' ', 'Mimic', 'House of Nobles', 'enchantment', ' ', 1, 1, 0, 0, 'Enchanted creature gets the same subtype(s) as target creature that is in the same front as the enchanted creature.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (16, 0.04, '2011-07-21 20:21:09', 'irrevenant', 'playtest', ' ', 'Remnants rise', 'Undead', 'enchantment', 'Unit', 2, 0, 0, 0, 'When enchanted creature is put into graveyard you may put into play a creature of equal or lower cost from your hand into the same front as the enchanted creature left.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (17, 0.04, '2011-05-11 19:56:55', 'irrevenant', 'playtest', ' ', 'Loyalty for Sale', 'House of Nobles', 'enchantment', ' ', 4, 2, 0, 0, 'Once per each players turn the enchanted player may lower target players threshold points with 1 for every 2 gold that the enchanted player pays. The enchanted player must also sacrifice a resource once every turn this ability is used.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (18, 0.05, '2011-08-01 15:51:03', 'irrevenant', 'playtest', ' ', 'Seasons Provision', 'Gaia', 'equipment', 'Other', 0, 1, 0, 0, 'Sacrifice Seasons Provision: Prevent all damage that was dealt to its carrier during this turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (19, 0.06, '2011-06-07 16:33:05', 'irrevenant', 'playtest', ' ', 'All are equal', 'Red Banner', 'spell', ' ', 0, 1, 0, 0, 'All abilities and effects that affect only one specific faction apply to all factions until the end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (20, 0.02, '2011-04-25 00:29:28', 'DaBASCHT', 'rejected', ' ', 'Donations for Recovery', 'Gaia', 'event', ' ', 0, 0, 0, 0, ' ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (21, 0.03, '2011-04-24 09:59:19', 'pennomi', 'playtest', ' ', 'Merman Hoplite', 'Gaia', 'unit', 'Merfolk', 3, 0, 0, 4, '<i>Guard</i> (This creature can defend against multiple attackers.)', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (22, 0.02, '2011-04-24 09:22:18', 'irrevenant', 'rejected', ' ', 'Ceasefire', 'Gaia', 'event', ' ', 0, 0, 0, 0, 'No units may attack this turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (23, 0.03, '2011-04-24 10:14:22', 'pennomi', 'playtest', ' ', 'Merman Brawler', 'Gaia', 'unit', 'Merfolk', 3, 0, 2, 2, 'Whenever Merman Brawler damages an enemy place a stun token on that enemy. When the enemy would be unmarked and while there are stun tokens on it, remove a stun token instead of unmarking it.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (24, 0.03, '2011-05-11 19:47:53', 'Q_x', 'playtest', ' ', 'Sudden Income', 'House of Nobles', 'event', ' ', 4, 2, 0, 0, 'Each of the target player''s resource piles gains +1 gold until end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (25, 0.03, '2011-04-24 10:44:02', 'Q_x', 'playtest', ' ', 'Green Shield', 'Gaia', 'event', ' ', 2, 1, 0, 0, 'Prevent all damage to target defender. It also gets +1/+0 until end of battle.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (26, 0.04, '2011-08-01 14:58:54', 'snowdrop', 'playtest', ' ', 'Doubt the Violence', 'Gaia', 'event', ' ', 3, 0, 0, 0, 'Target attacker is placed on top of its owners Army Deck. If it costs 3 or less and it has no local attacking allies it is discarded instead. All damage to the defender(s) is resolved as normal.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (27, 0.03, '2011-04-24 09:42:35', 'pennomi', 'playtest', 'cards/27-1.png', 'Dryad''s Flute', 'Gaia', 'equipment', 'Other', 3, 2, 0, 0, '4, [m]: Remove target non-Gaian attacker from combat before it''s defender is declared. It remains marked.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (28, 0.03, '2011-04-24 11:31:16', 'pennomi', 'playtest', ' ', 'March of the Bones', 'Undead', 'enchantment', 'Front', 4, 2, 0, 0, 'Draw a card whenever an ally Undead creature is discarded from one of your fronts.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (29, 0.04, '2011-04-24 10:57:20', 'Q_x', 'playtest', ' ', 'Living Trees', 'Gaia', 'event', ' ', 3, 1, 0, 0, 'Every unused resource pile becomes a Tree Creature until end of turn with x/x, where X is the amount of resources in the RP. Discard one resource card from the RP for each 2 damage it receives.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (30, 0.04, '2011-08-01 14:45:46', 'Q_x', 'playtest', ' ', 'Camoflage Coat', 'Gaia', 'equipment', 'Armor', 2, 1, 0, 0, 'Equipped creature gets +1/+0 when defending. While it is not defending it has +0/+1.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (31, 0.03, '2011-04-24 10:40:35', 'Ravenchild', 'playtest', ' ', 'Secret Path', 'Red Banner', 'event', ' ', 3, 2, 0, 0, 'If you attack with an equal number of creatures on both fronts then target player may not assign any defenders to any of the your attacking creature in your target front.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (32, 0.04, '2011-04-24 09:46:27', 'snowdrop', 'playtest', 'cards/32-1.png', 'Elvish Captain', 'Gaia', 'unit', 'Elf, Leader', 5, 0, 3, 3, 'All ally Gaian creatures gain +0/+1 while defending.\r\n[m]:Unmark target ally.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (79, 0.02, '2011-08-01 16:15:30', 'Ether', 'discuss', ' ', 'Hard times', 'House of Nobles', 'spell', ' ', 0, 0, 0, 0, 'Mark one of yours and one of another player''s resource piles as occupied.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (33, 0.05, '2011-08-01 15:30:25', 'Ether', 'playtest', ' ', 'Longing for peace', 'Gaia', 'event', ' ', 4, 2, 0, 0, 'Until end of current turn and the next players turn no attackers can be declared in target front.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (34, 0.04, '2011-04-24 11:28:57', 'verbalshadow', 'rejected', ' ', 'Wolf Rider ', 'Red Banner', 'unit', 'Goblin, Leader, Rider', 5, 0, 4, 4, 'Ally Red Banner Units gain +1/0 against House of Noble units and Leader subtypes this ability stacks.\r\nWolf Rider may Block 2 attackers when it does it become one 2/2 Goblin and one 2/2 Wolf until the end of Round. If either Goblin or Wolf are destroyed, Wolf Rider does not unmark during the next unmark phase.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (35, 0.03, '2011-04-24 10:36:30', 'verbalshadow', 'playtest', ' ', 'Goblin Altruist', 'Red Banner', 'unit', 'Goblin - Guard', 2, 0, 0, 2, 'You may sacrifice Goblin Altruist at any time to counter an Event that costs 3 or less.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (36, 0.03, '2011-04-24 11:20:38', 'verbalshadow', 'playtest', ' ', 'Orc Blacksmith', 'Red Banner', 'unit', 'Orc - Artisan', 3, 1, 2, 2, 'Orc Blacksmith does not have to unmark. Put one material token on Orc Blacksmith each turn it doesn''t unmark.\r\n\r\nRemove all material tokens, [m]: Search your Army deck for any weapon or armor that costs equal to or less than the removed material tokens. Equip target creature with it for free. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (37, 0.05, '2011-07-28 01:14:28', 'verbalshadow', 'playtest', ' ', 'Arms Merchant', 'House of Nobles', 'unit', 'Human', 2, 2, 0, 1, 'x, [m]: Take a target Equipment from any front and attach it to a creature in the same front as the Arms Merchant. X is double the cost of the target Equipment.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (38, 0.04, '2011-08-07 04:54:28', 'verbalshadow', 'playtest', ' ', 'Goblin Reserve', 'Red Banner', 'unit', 'Goblin - Reserve', 2, 0, 1, 1, '<i>Static Defense</i> (Creature''s DEF may never exceed its base value.) \r\n\r\nWhen Goblin Reserve comes into play you may put another creature with the Reserve subtype into play in the same front from your hand without paying its cost.', 'We travel in packs.');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (39, 0.06, '2011-08-01 14:41:39', 'snowdrop', 'playtest', ' ', 'Bound by Love', 'Gaia', 'enchantment', ' ', 3, 0, 0, 0, 'Target an ally. Search your deck for a Gaian Creature with a cost of 3 or less and place it local to the ally for free. The creature will follow the ally <i>wherever</i> it''s placed. Movement marks it as usual.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (40, 0.04, '2011-04-24 10:23:39', 'snowdrop', 'playtest', ' ', 'Serenity', 'Gaia', 'event', ' ', 1, 2, 0, 0, 'Target combating non-Gaian creature doesn''t unmark next turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (41, 0.04, '2011-04-24 09:07:53', 'verbalshadow', 'playtest', ' ', 'First Strike', 'Red Banner', 'event', ' ', 2, 2, 0, 0, 'Ally Red Banner creatures in target front have <i>Offensive Initiative</i> until end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (42, 0.03, '2011-04-24 10:19:18', 'Gallaecio', 'playtest', ' ', 'Debt collector', 'House of Nobles', 'unit', 'Human, civilian', 2, 1, 1, 1, '[m]: Your smallest resource pile is considered to have +1 gold until end of turn.\r\n\r\nPacifist (This creature can not attack.)', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (54, 0.03, '2011-07-19 21:13:04', 'Sweep', 'playtest', ' ', 'Resiliant Serker', 'House of Nobles', 'unit', 'Dwarf', 3, 0, 0, 4, 'Rage (this unit gets +1/0 for each point of damage currently on it)\r\n\r\n[m], 3: Resiliant Serker can defend against an additional attacker and gets 0/+2.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (43, 0.05, '2011-04-24 11:10:29', 'snowdrop', 'playtest', ' ', 'Scrap Gatherer', 'Red Banner', 'unit', 'Goblin - Reserve', 2, 1, 0, 2, 'Scrap Gatherer can never have an attack value and modifiers of it''s ATK have no effect. He can also not use any equipment.\r\n\r\n3, [m]: Place target fallen equipment on the Scrap Gatherer. This ability precedes enemy creatures picking it up from their fallen allies. \r\n\r\n[m]: Equip target ally creature with target equipment from the Scrap Gatherer.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (44, 0.06, '2011-05-11 19:45:52', 'snowdrop', 'playtest', ' ', 'Orc Commander', 'Red Banner', 'unit', 'Orc - Leader', 5, 0, 3, 2, 'Ally Goblins may move even though they are marked.\r\n\r\n[m], Sacrifice a Goblin: Deal 1 damage to target creature.', 'For the collective!');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (45, 0.03, '2011-05-11 19:46:56', 'snowdrop', 'playtest', ' ', 'Tax Records', 'Empire', 'artifact', 'Other', 2, 2, 0, 0, 'Every turn you don''t put a resource card into play target RP is considered to have +1 resources in it until end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (46, 0.08, '2011-05-29 15:42:22', 'Ether', 'playtest', ' ', 'Orc Drummer ', 'Red Banner', 'unit', ' ', 6, 2, 2, 2, 'When Orc Drummmer comes into play you may put into play any amount of Red Banner creatures from hand with the total cost of 4 into the same front as Orc Drummer for free & marked. \r\n\r\n[m]: Ally goblin gets +1/0 until end of turn.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (47, 0.02, '2011-07-19 20:44:22', 'Ether', 'discuss', ' ', 'Winds of Change', 'Red Banner', 'spell', ' ', 4, 0, 0, 0, 'This card may played only if you have played no other cards during the turn. Discard all cards in hand and then draw up to 7 new cards. End your turn immediately after that. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (48, 0.06, '2011-05-11 19:41:43', 'Ether', 'playtest', ' ', 'Natural Disaster', 'Undead', 'event', ' ', 4, 0, 0, 0, 'Pick one of your unused RPs. Put two Shadowguild creatures residing in it with cost of 3 or less each into play in target front. Discard the rest of that RP.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (49, 0.04, '2011-08-01 13:13:29', 'Ether', 'playtest', ' ', 'Arknym Half-tree', 'Gaia', 'unit', ' ', 5, 3, 2, 2, 'While in combat Arknym Half-tree can only die if it has been dealt damage by a Caster, Legend or Leader.\r\n\r\nArknym Half-tree may not get its combat\r\nstats made greater in any way.', 'Beyond camouflage is Arknym.');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (50, 0.06, '2011-08-01 14:25:50', 'Ether', 'playtest', ' ', 'Thunder Arkbalist', 'Gaia', 'unit', ' artifact', 7, 3, 5, 3, 'When Thunder Arkbalist attacks, mark target ally. Discard Thunder Arkbalist if the marked creature is discarded the same turn it marked.\r\n\r\nOffensive strike.\r\n\r\nRanged', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (51, 0.02, '2011-07-19 20:35:09', 'Ether', 'discuss', ' ', 'The One with Sharp Talons', 'Gaia', 'unit', ' ', 6, 1, 4, 4, 'Flying\r\n\r\nOffensive strike\r\n\r\nThe one with sharp talons may not attack unless you mark a local caster. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (52, 0.04, '2011-08-01 15:57:25', 'Ether', 'playtest', ' ', 'Pathfinders Touch', 'Gaia', 'enchantment', ' ', 3, 3, 0, 0, 'Target creature gets Pathfinder -  Only creatures with <i>Flying</i> or <i>Ranged</i> can defend against Pathfinder.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (53, 0.02, '2011-07-19 20:58:36', 'Ether', 'discuss', ' ', 'D''rgana', 'Red Banner', 'equipment', 'Weapon - Enchantment', 4, 0, 0, 0, 'The carrier recieves +1/+0.\r\n\r\nWhile attached the D''rgana can become unattached and act as a 3/1 creature instead of an equipment if it''s carrier is defending. If the D''rgana survived as a creature, re-attach it to the last creature that was equipped with it. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (55, 0.01, '2011-05-13 02:38:40', 'Sweep', 'concept', NULL, 'Liberated Giant', 'Red Banner', 'unit', 'Giant - Rebel', 5, 0, 6, 5, 'Rage (this unit gets +1 attack for each point of damage currently on it).\r\n\r\nThis unit must attack each turn.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (56, 0.02, '2011-07-19 14:43:15', 'Gallaecio', 'discuss', ' ', 'Servitude', 'Undead', 'spell', ' ', 2, 3, 0, 0, 'Sacrifice target creature in play. Put one Servitude token on up to two target ally Shadowguild creatures in the same front as the sacrificed creature. Whenever a creature with a Servitude token would be discraded, remove a servitude token instead.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (57, 0.02, '2011-07-19 14:54:39', 'Ether', 'discuss', ' ', 'Peoples Support', 'Red Banner', 'artifact', ' ', 3, 0, 0, 0, '[m]: When playing two cards with equal cost during the same turn you may put one of them into play for free. If one of them would be a creature it comes into play marked.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (58, 0.03, '2011-07-23 23:08:37', 'Ether', 'discuss', ' ', 'Shrine of Reduction', 'Empire', 'artifact', ' ', 3, 0, 0, 0, '[m]: Pay 1 gold less for target card that you are  about to put into play. If the card cost should become less than 1 for some reason, pay 1 instead.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (59, 0.02, '2011-07-23 23:05:47', 'verbalshadow', 'discuss', ' ', 'Waving Banners', 'Red Banner', 'artifact', ' ', 2, 2, 0, 0, '2: Target creature does not have to mark to attack.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (60, 0.01, '2011-07-22 05:58:13', 'Ether', 'concept', NULL, 'Sharp Blades', 'Red Banner', 'enchantment', NULL, 4, 3, NULL, NULL, 'All ally weapons have +1/0 during this turn.\r\n[m] to give them +2/0 instead', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (61, 0.03, '2011-07-23 22:58:46', 'Ether', 'discuss', ' ', 'Tribes Aid', 'Red Banner', 'event', ' ', 0, 1, 0, 0, 'For every card in target RP you may play a card from your hand for free. On end of turn you must  discard all cards left in your hand and also the RP you targeted previously.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (62, 0.01, '2011-07-22 06:03:50', 'Ether', 'concept', NULL, 'Summoning', 'Undead', 'unit', NULL, 5, 3, NULL, NULL, 'Discard one of your creatures to play two creatures for free. The creatures you will play can''t have cost higher than the discarded one.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (63, 0.04, '2011-07-23 22:44:52', 'Ether', 'discuss', ' ', 'Sun Eclipse', 'Undead', 'event', ' ', 3, 1, 0, 0, 'Target attacker deals it''s damage to target attacking ally instead of the defender.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (64, 0.02, '2011-07-23 22:55:30', 'Ether', 'rejected', ' ', 'Diplomacy', 'House of Nobles', 'event', ' ', 0, 0, 0, 0, '[m][m] solve the battle without drawing damage', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (65, 0.04, '2011-07-23 23:00:32', 'Ether', 'discuss', ' ', 'Dark Ritual', 'Undead', 'spell', ' ', 0, 0, 0, 0, 'Sacrifice creatures from your Kingdom that are worth x gold summed up in total. Discard target enemy creature that costs x - 3. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (66, 0.01, '2011-07-22 06:10:07', 'Ether', 'concept', NULL, 'Goblin believer', 'Red Banner', 'unit', NULL, 5, 2, 1, 2, 'This unit gains +2/+1 when fighting together with an ally caster.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (67, 0.01, '2011-07-22 06:11:14', 'Ether', 'concept', NULL, 'Young Goblin', 'Red Banner', 'unit', NULL, 3, 0, 1, 1, 'Gains +2/0 when fighting together with an ally orc.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (68, 0.01, '2011-07-22 06:13:46', 'Ether', 'concept', NULL, 'Mantrap', 'Undead', 'equipment', NULL, NULL, NULL, NULL, NULL, 'Use on blocking unit. The unit can''t block and is hit with 4/0 power. Discard this card after using it.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (69, 0.01, '2011-07-22 06:16:13', 'Ether', 'concept', NULL, 'Scarecrow', 'Undead', 'unit', 'caster', 4, NULL, 1, 3, '[m] attackers have -1/0 (does not stack!)', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (70, 0.05, '2011-08-02 12:59:22', 'snowdrop', 'discuss', ' ', 'My brothers keeper', 'Red Banner', 'event', ' ', 1, 1, 0, 0, 'Remove target ally creature from combat. All combat damage that has been received by the creature and all effects that have targeted the same creature are instead transferred to a local Red Banner creature. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (71, 0.02, '2011-08-01 16:18:17', 'snowdrop', 'concept', ' ', 'Last Stand', 'Red Banner', 'spell', ' ', 0, 0, 0, 0, 'Until end of turn all allies in target front get +x/0, where x is equal to 2 if you have 9 or less influence or x is equal to 3 if you have 3 or less influence. Creatures in that front that are going to attack this turn don''t have to mark.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (72, 0.01, '2011-07-24 04:24:22', 'snowdrop', 'concept', NULL, 'Matter is not', 'Gaia', 'enchantment', NULL, NULL, NULL, NULL, NULL, 'Enchanted creature can''t be the target of Equipment and is also immune to damage and any other effects of all Equipment.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (73, 0.02, '2011-08-02 13:18:09', 'snowdrop', 'concept', ' ', 'Treachery', 'House of Nobles', 'spell', ' ', 0, 3, 0, 0, 'Pay double the cost for target enemy marked creature. It''s owner shuffles it back into his/her army deck. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (74, 0.02, '2011-08-02 12:48:04', 'snowdrop', 'discuss', ' ', 'Espionage', 'House of Nobles', 'event', ' ', 2, 2, 0, 0, 'Look at the cards in target players hand.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (75, 0.01, '2011-07-24 12:21:08', 'snowdrop', 'concept', NULL, 'Reallocation', 'Empire', 'event', NULL, 2, 1, NULL, NULL, 'Target used RP becomes unused.', NULL);
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (76, 0.02, '2011-07-24 13:06:22', 'snowdrop', 'discuss', 'cards/76-1.png', 'Shyde', 'Gaia', 'unit', 'Caster', 0, 1, 1, 1, 'When Shyde leaves play you may search your Army Deck for an Enchantment that costs 5 or less. If you do, put it into play for free & shuffle the deck.\r\n\r\n<i>Flying</i>', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (77, 0.03, '2011-08-02 13:12:15', 'snowdrop', 'concept', ' ', 'Imperial Banner', 'Empire', 'artifact', ' ', 1, 3, 0, 0, 'Imperial Banner counts as +1 towards your total sum of Empire Threshold points.\r\n\r\nSacrifice Imperial Banner: Put an Empire creature that costs 3 or less from your hand into play for free.', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (78, 0.07, '2011-08-02 12:43:02', 'snowdrop', 'concept', ' ', 'Defenders Cloak', 'Gaia', 'equipment', 'magical', 4, 2, 0, 0, 'Once per turn when equipped creature defends you may gain 2 influence. Your total influence can never become more than the initial amount you started the game with. ', ' ');
INSERT INTO `wt_cs_cards` (`id`, `revision`, `date`, `author`, `status`, `image`, `cardname`, `faction`, `type`, `subtype`, `cost`, `threshold`, `attack`, `defense`, `rules`, `flavor`) VALUES (80, 0.03, '2011-08-07 17:19:38', 'snowdrop', 'concept', ' ', 'Embargo', 'House of Nobles', 'enchantment', ' ', 3, 0, 0, 0, 'Enchanted player must pay +1 in additions to Artifacts cost. \r\n\r\nEnchanted player sacrifices 3 resource cards from one RP: Discard Embargo.', ' ');

CREATE TABLE IF NOT EXISTS `wt_cs_users` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(16) collate utf8_unicode_ci default NULL,
  `password` char(32) collate utf8_unicode_ci default NULL,
  `email` char(64) collate utf8_unicode_ci default NULL,
  `role` enum('User','Moderator','Developer','Lead Developer','Administrator','Banned') collate utf8_unicode_ci default 'User',
  `lastvisit` timestamp NULL default NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=13 ;

INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (1, 'admin', 'cd13b6a6af66fb774faa589a9d18f906', '', 'Administrator', '2011-02-08 18:42:36', '2011-02-05 18:58:08');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (2, 'pennomi', 'eab0d156d2ac448cdbe8167e401da1c3', 'pennomi@wtactics.org', 'Lead Developer', '2011-04-09 22:19:23', '2011-02-05 19:01:08');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (3, 'Ether', '98abd3c3f26c203580c61858a63a9165', 'luke.jastrzebski@gmail.com', 'Lead Developer', '2011-08-01 14:51:11', '2011-02-06 20:49:26');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (4, 'DaBASCHT', 'efa619f95f1a1d497ffd383e16e36093', 'dabascht@gmail.com', 'User', '2011-02-27 15:03:47', '2011-02-06 21:16:19');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (5, 'TorbenBeta', '0b87d66b88c72957dfea8c9605016442', 'Torben1994@gmx.de', 'User', '2011-10-05 08:56:55', '2011-02-07 20:53:11');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (6, 'verbalshadow', 'cc5290657d39d0f877902895b9426101', 'verbalshadow@gmail.com', 'Lead Developer', '2011-10-16 16:46:37', '2011-02-07 23:42:11');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (7, 'Gallaecio', '6d135c867e26184b97e3b7e8529e7787', 'adriyetichaves@gmail.com', 'User', '2011-06-20 16:24:14', '2011-02-09 14:42:41');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (8, 'snowdrop', 'cd13b6a6af66fb774faa589a9d18f906', 'snowdrop@wtactics.org', 'Lead Developer', '2011-08-06 04:29:13', '2011-02-09 20:36:59');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (9, 'Ravenchild', '6fd9c4b18ccdf18195e2238a05feb2b3', 'notions@web.de', 'User', '2011-03-10 15:36:45', '2011-03-04 07:56:55');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (10, 'aspidites', '9117f789530764552674464c18f2b0a4', 'emarshall85@gmail.com', 'User', '2011-04-13 06:25:59', '2011-03-13 19:50:09');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (11, 'Sweep', 'd26467e724a32ce0af9d0c337a40be0f', 'sweepymcsweepalot@gmail.com', 'User', '2011-05-13 02:32:50', '2011-05-13 02:32:35');
INSERT INTO `wt_cs_users` (`id`, `name`, `password`, `email`, `role`, `lastvisit`, `date`) VALUES (12, 'lasic', '59b2e817977bddf92397fa3abf37f5f8', 'lasic1@laposte.net', 'User', NULL, '2011-10-30 20:30:48');

COMMIT;
